services:
  server:
    build: ./server
    container_name: soulsync-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - python
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CLIENT_URL=http://client:5173
    volumes:
      - ./server:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  python:
    build: ./python-server
    container_name: soulsync-python
    ports:
      - "8000:8000"
    env_file:
      - ./python-server/.env

  client:
    build: ./client
    container_name: soulsync-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules

  redis:
    image: redis:7
    container_name: soulsync-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
